### ISSUE TITLE
Phase 1 Ideas

### ISSUE THREAD

**Issue by invisibleroads** [crosscompute/conference-planner#1]
### Input

- URI to repository or URI to CSV

### Output

- Markdown with upcoming proposal deadlines and conference dates

```markdown
# Conference Planner

## Upcoming Proposal Deadlines

### Friday, January 2, 2023
- [Conference A Talk Proposals Due](https://link-to-talk-cfp.com)

### Friday, March 20, 2023
- [Conference B Talk Proposals Due](https://link-to-talk-cfp.com)

## Upcoming Conferences

### Friday, February 2, 2023
- [Conference A](https://link-to-conference.com)

### Friday, June 20, 2023
- [Conference B](https://link-to-conference.com)
```

## Tasks

- [x] Accept URI to repository of conferences (e.g. https://github.com/python-organizers/conferences)
- [x] [Postponed to Phase 2] Accept URI to CSV such as a Google Sheet or Airtable
- [x] Show only upcoming conferences based on today's date; do not show past conferences
- [x] Have the script run once a day (interval: 1 day)

**Comment by invisibleroads** [comment]
- [x] Default to output mode on automation page
